apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: development
resources:
  - ../../base/converter-ui
images:
  - name: ghcr.io/dasbaumwolltier/converter-ui
    newTag: development-20230111-2009
