apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: staging
resources:
  - ../../base/converter-ui
patchesStrategicMerge:
  - patches/ingress.yaml
images:
  - name: ghcr.io/dasbaumwolltier/converter-ui
    newTag: staging-20230111-2031
