apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: development
resources:
  - ../../base/converter-ui
images:
  - name: ghcr.io/dasbaumwolltier/converter-ui
    newTag: ""
spec:
  template:
    spec:
      containers:
        - image: ""
