apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: staging

resources:
  - ../../base/converter-backend

images:
  - name: ghcr.io/dasbaumwolltier/converter-backend
    newTag: 2022-11-01