apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: development
resources:
  - ../../base/converter-backend
images:
  - name: ghcr.io/dasbaumwolltier/converter-backend
    newTag: development-20230111-2014
