apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: converter-ui
spec:
  rules:
  - host: localhost
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: converter-ui
            port:
              number: 80