apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: production
resources:
  - ../../base/converter-ui
images:
  - name: ghcr.io/dasbaumwolltier/converter-ui
    newTag: 2022-01-01
