apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - resources/deployment.yaml
  - resources/ingress.yaml
  - resources/service.yaml

images:
  - name: ghcr.io/dasbaumwolltier/converter-backend
    newTag: 2022-11-01