apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: production
resources:
  - ../../base/converter-backend
patchesStrategicMerge:
  - patches/ingress.yaml
images:
  - name: ghcr.io/dasbaumwolltier/converter-backend
    newTag: production-20230111-2031
