# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: build
on:
  push:
    branches:
      - development
      - staging
      - production

jobs:
  prepare:
    runs-on: ubuntu-latest
    outputs:
      release_date: ${{ steps.set_date.outputs.date }}
      environment: ${{ steps.check_environment.outputs.environment }}
    steps:
      - id: set_date
        run: echo "date=$(date +'%Y%m%d-%H%M')" >> $GITHUB_OUTPUT
      - id: check_environment
        run: echo "environment=$(echo $GITHUB_REF_NAME)" >> $GITHUB_OUTPUT

  build-frontend:
    runs-on: ubuntu-latest
    needs: prepare
    steps:
      - name: Clone
        uses: actions/checkout@v3

      - name: Login
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Image name
        run: echo "IMAGE_NAME=ghcr.io/${{ secrets.DOCKER_USERNAME }}/converter-ui:${{needs.prepare.outputs.environment}}-${{needs.prepare.outputs.release_date}}" >> $GITHUB_ENV  && echo "TAG_NAME=${{needs.prepare.outputs.environment}}-${{needs.prepare.outputs.release_date}}" >> $GITHUB_ENV

      - name: Build
        run: |
          docker build ./converter-ui --file ./converter-ui/Dockerfile --tag ${{ env.IMAGE_NAME }} && \
          docker push ${{ env.IMAGE_NAME }}
      
      - name: Set Deployment
        uses: mikefarah/yq@master
        with: 
          cmd: tag=${{env.TAG_NAME}} yq -i '.images[0].newTag = strenv(image)' gitops/${{needs.prepare.outputs.environment}}/converter-ui/kustomization.yaml

      - name: Upload kustomization.yaml
        uses: actions/upload-artifact@v3
        with:
          name: converter-ui-kustomization-yaml
          path: gitops/${{needs.prepare.outputs.environment}}/converter-ui/kustomization.yaml

  build-backend:
    runs-on: ubuntu-latest
    needs: prepare
    steps:
      - name: Clone
        uses: actions/checkout@v3

      - name: Login
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Image name
        run: echo "IMAGE_NAME=ghcr.io/${{ secrets.DOCKER_USERNAME }}/converter-backend:${{needs.prepare.outputs.environment}}-${{needs.prepare.outputs.release_date}}" >> $GITHUB_ENV && echo "TAG_NAME=${{needs.prepare.outputs.environment}}-${{needs.prepare.outputs.release_date}}" >> $GITHUB_ENV

      - name: Build
        run: |
          docker build ./converter --file ./converter/Dockerfile --tag ${{ env.IMAGE_NAME }} && \
          docker push ${{ env.IMAGE_NAME }}
      
      - name: Set Deployment
        uses: mikefarah/yq@master
        with: 
          cmd: tag=${{env.TAG_NAME}} yq -i '.images[0].newTag = strenv(image)' gitops/${{needs.prepare.outputs.environment}}/converter-backend/kustomization.yaml

      - name: Upload kustomization.yaml
        uses: actions/upload-artifact@v3
        with:
          name: converter-backend-kustomization-yaml
          path: gitops/${{needs.prepare.outputs.environment}}/converter-backend/kustomization.yaml


  update-kustomizations:
    runs-on: ubuntu-latest
    needs: [prepare, build-frontend, build-backend]

    steps:
      - name: Clone
        uses: actions/checkout@v3

      - name: Download converter-ui-kustomization-yaml
        uses: actions/download-artifact@v3
        with:
          name: converter-ui-kustomization-yaml
          path: gitops/${{needs.prepare.outputs.environment}}/converter-ui

      - name: Download converter-backend-kustomization-yaml
        uses: actions/download-artifact@v3
        with:
          name: converter-backend-kustomization-yaml
          path: gitops/${{needs.prepare.outputs.environment}}/converter-backend
          
      - name: Commit deployment Files
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "ci: update deployment"
          skip_checkout: true